# Simulation
episodes: 100
episode_limit: 300
random_seed: 42

# General
max_results_length: 10 # for plotting
images_path: "/home/ubuntu/spectrum_sharing/Simulations/"
log_path: "/home/ubuntu/spectrum_sharing/Logging/"

# Scene and Sionna
num_rx: 20
max_depth: 3
sharing_carrier_freq: 7425e6
primary_subcarrier_spacing: 15e3 # WiFi 6 subcarrier spacing would be 78.125, may need to change resource grid to properly change
sharing_subcarrier_spacing: 30e3 # Changing this will change the number of slots per frame
primary_fft_size: 120 # needs to be a power of 12RBs - will be rounded to power of 2 fft internally
sharing_fft_size: 324
batch_size: 1000 # also corresponds to time between episodes when subcarrier_spacing is considered
ebno_db: 2.0
cell_size: 3

# Model and training
training_batch_size: 10 # in timesteps
target_network_update_freq: 5 # in episodes
buffer_max_size: 100000
gamma: 0.99
epsilon_start: 0.95
epsilon_min: 0.1
epsilon_decay: 0.995
learning_rate: 0.001

# Transmitters
transmitters:
    tx0:
        name: "tx0"
        position: [-16, 23, 25] # transmitter and receiver structure needs to be the same - may need to include Doppler
        direction: [0, 0, 0]
        orientation: [0, 0, 0]
        color: [1, 0, 0]
        primary_power: 17.0
        sharing_power: 17.0
        look_at: [-30, 23, 10]
        mu_pa: 0.4
        primary_carrier_freq: 4145e6

    tx1:
        name: "tx1"
        position: [32, 10, 21]
        direction: [0, 0, 0]
        orientation: [0, 0, 0]
        color: [1, 0, 0]
        primary_power: 35.0
        sharing_power: 35.0
        look_at: [32, 0, 10]
        mu_pa: 0.5
        primary_carrier_freq: 3425e6


    # tx2:
    #     name: "tx2"
    #     position: [20, -40, 25] # transmitter and receiver structure needs to be the same - may need to include Doppler
    #     direction: [0, 0, 0]
    #     orientation: [0, 0, 0]
    #     color: [1, 0, 0]
    #     primary_power: 26.0
    #     sharing_power: 26.0
    #     look_at: [0, 0, 0]
    #     mu_pa: 0.2
    #     primary_carrier_freq: 5000e6